name: Integration
on:
  push:
    branches: [main]
  pull_request_target:
    types: [opened, edited, reopened, synchronize, review_requested, assigned]
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get current branch
        id: check_branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "branch=$branch" >> $GITHUB_OUTPUT
          echo "Current Branch is $branch."
    outputs:
      branch: ${{ steps.check_branch.outputs.branch }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - run: npm install

      - name: Set Version
        id: version
        run: |
          packageVersion=$(npx -c 'echo "$npm_package_version"')
          echo "version=$packageVersion" >> $GITHUB_OUTPUT

      - name: Build vsix
        run: npx vsce package ${{ steps.version.outputs.version }} --no-git-tag-version -o demo-vscode-${{ steps.version.outputs.version }}.vsix --pre-release

      - uses: actions/upload-artifact@v3
        with:
          path: "*.vsix"

  integration:
    if: needs.check.outputs.branch == 'main'
    runs-on: ubuntu-latest
    needs: [check, build]
    steps:
      - uses: actions/download-artifact@v3
        
      - name: Release to VSCode Marketplace as pre release
        run: npx vsce publish --packagePath $(find . -iname *.vsix) --pre-release
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
