name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - run: npm install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_arch: ${{ matrix.npm_config_arch }}

      - run: npx vsce package ${{ github.ref_name }} --no-git-tag-version

      - uses: actions/upload-artifact@v2
        with:
          path: "*.vsix"

  release:
    runs-on: ubuntu-latest
    needs: build
    if: success() && startsWith( github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v2

      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: $(find . -iname *.vsix)

      - name: Release to VSCode Marketplace
        run: npx vsce publish --packagePath $(find . -iname *.vsix)
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}