name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith( github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - run: npm install

      - name: Build vsix
        run: npx vsce package ${{ github.ref_name }} --no-git-tag-version -o demo-vscode-${{ github.ref_name }}.vsix

      - uses: actions/upload-artifact@v3
        with:
          path: "*.vsix"

  release:
    runs-on: ubuntu-latest
    needs: build
    if: success() && startsWith( github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v3

      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifact/demo-vscode-${{ github.ref_name }}.vsix
          generate_release_notes: true

      - name: Release to VSCode Marketplace
        run: npx vsce publish --packagePath $(find . -iname *.vsix)
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Release to Open VSX
        run: npx ovsx publish ./artifact/demo-vscode-${{ github.ref_name }}.vsix
        continue-on-error: true
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT}}